_commit: v2.0.0
_src_path: gh:mopidy/mopidy-ext-template
author_email: stein.magnus@jodal.no
author_full_name: Stein Magnus Jodal
dist_name: mopidy-local
ext_name: local
github_username: mopidy
short_description: Mopidy extension for playing music from your local music archive
